# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmatapi', '0003_auto_20170309_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('title', 'performer')]),
        ),
    ]
