# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmatapi', '0007_auto_20170309_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='start_time',
            new_name='start',
        ),
    ]
