# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmatapi', '0008_auto_20170309_2209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='play',
            unique_together=set([('channel', 'start')]),
        ),
    ]
